{ lib, ... }:

let
  # Its own colours, literal, matching desktop/glass/palette.nix. This module
  # used to take the repo-wide `themes` attrset, generate a .toml per palette
  # and register a theme-set hook to swap between them — a file manager that
  # runs fine over ssh following a desktop's colour scheme, on every host that
  # imported it including the headless ones.
  #
  # One palette now, so there is nothing to switch and no hook to register.
  t = {
    bg          = "#101113";
    surface     = "#191B1E";
    selection   = "#26282C";
    fg          = "#E8EAEC";
    fishPrimary = "#C8CBCF";
  };

  # Glass is the only palette without an upstream superfile theme, so it gets
  # one written here. Two reasons it can't just borrow a built-in:
  #
  #  - ghostty-glass runs at background-opacity 0.92 with blur. Every built-in
  #    theme fills its panels with an opaque colour, so superfile came out as a
  #    solid rectangle over a translucent window — the same seam nvim had.
  #    superfile has a global `transparent_background` flag, but it is global:
  #    it would flatten the other four palettes too, and it also strips the
  #    modal background, which should stay raised. Empty bg strings reach
  #    `lipgloss.Color("")` (no colour) per-theme instead, which leaves the
  #    other presets alone.
  #  - it was pointed at `onedark`, which is blue-leaning — the one thing this
  #    palette is explicitly trying not to be.
  #
  # Grounds are empty; raised surfaces (modal) and selections keep an opaque
  # fill on purpose, matching how the nvim glass snippet treats floats.
  #
  # Accents are the ghostty ANSI palette, restated here because the palette
  # above carries only ground and text colours.
  glassTheme = ''
    # Glass — generated by modules/home/cli/superfile.nix. Do not edit here;
    # superfile only overwrites files that exist in its own embedded set, so
    # this one survives its theme extraction.

    code_syntax_highlight = "github-dark"

    # ========= Border =========
    file_panel_border = "${t.selection}"
    sidebar_border = "${t.selection}"
    footer_border = "${t.selection}"

    # ========= Border Active =========
    file_panel_border_active = "#9FB0C2"
    sidebar_border_active = "#B7A9C6"
    footer_border_active = "#8FCFB4"
    modal_border_active = "#9CBCC0"

    # ========= Background (bg) =========
    # Empty = no colour = the terminal's own translucent ground shows through.
    full_screen_bg = ""
    file_panel_bg = ""
    sidebar_bg = ""
    footer_bg = ""
    modal_bg = "${t.surface}"

    # ========= Foreground (fg) =========
    full_screen_fg = "${t.fishPrimary}"
    file_panel_fg = "${t.fishPrimary}"
    sidebar_fg = "${t.fishPrimary}"
    footer_fg = "${t.fishPrimary}"
    modal_fg = "${t.fg}"

    # ========= Special Color =========
    cursor = "${t.fg}"
    correct = "#8FCFB4"
    error = "#E8837A"
    hint = "#9CBCC0"
    cancel = "#D8BE96"
    gradient_color = ["#9FB0C2", "#B7A9C6"]

    # ========= File Panel Special Items =========
    file_panel_top_directory_icon = "#D8BE96"
    file_panel_top_path = "#B6C4D4"
    file_panel_item_selected_fg = "${t.fg}"
    file_panel_item_selected_bg = "${t.selection}"

    # ========= Sidebar Special Items =========
    sidebar_title = "#9FB0C2"
    sidebar_item_selected_fg = "${t.fg}"
    sidebar_item_selected_bg = "${t.selection}"
    sidebar_divider = "#3B3E44"

    # ========= Modal Special Items =========
    modal_cancel_fg = "${t.bg}"
    modal_cancel_bg = "#E8837A"

    modal_confirm_fg = "${t.bg}"
    modal_confirm_bg = "#8FCFB4"

    # ========= Help Menu =========
    help_menu_hotkey = "#9CBCC0"
    help_menu_title = "#B7A9C6"
  '';

in
{
  programs.superfile = {
    enable = true;
    settings = {
      editor = "nvim";
      dir_editor = "nvim";
      ignore_missing_fields = true;
      theme = "active";
    };
  };

  # superfile reads themes from ~/.config/superfile/theme, a directory it
  # populates itself on first launch. Writing into it is safe: its extraction
  # only creates files that exist in its embedded set, and `glass.toml` is not
  # one of them.
  xdg.configFile."superfile/theme/glass.toml".text = glassTheme;

  # `theme = "active"` above, so point active.toml at the one palette this
  # module ships. superfile extracts its built-in themes into this directory
  # lazily on first launch, which is why the symlink is made at activation
  # rather than written as a config file — the directory may not exist yet.
  #
  # This used to resolve a name out of ~/.local/state/quickshell/active-theme
  # (what theme-set wrote) with ~/.config/hypr/theme.conf as a fallback, then
  # map it through a per-palette case statement. All of that existed to follow
  # a desktop, and a preset that never switches left it resolving to whatever
  # hypr was last set to — which is how it ended up on onedark under glass.
  home.activation.syncSuperfileTheme = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    SPF_THEMES="$HOME/.config/superfile/theme"
    if [ -f "$SPF_THEMES/glass.toml" ]; then
      ln -sf "$SPF_THEMES/glass.toml" "$SPF_THEMES/active.toml"
    fi
  '';
}
