{ pkgs, lib, themes, ... }:

let
  superfileThemeMap = lib.mapAttrs (_: t: t.superfileTheme or "hacks") themes;

  # Glass is the only palette without an upstream superfile theme, so it gets
  # one written here. Two reasons it can't just borrow a built-in:
  #
  #  - ghostty-glass runs at background-opacity 0.92 with blur. Every built-in
  #    theme fills its panels with an opaque colour, so superfile came out as a
  #    solid rectangle over a translucent window — the same seam nvim had.
  #    superfile has a global `transparent_background` flag, but it is global:
  #    it would flatten the other four palettes too, and it also strips the
  #    modal background, which should stay raised. Empty bg strings reach
  #    `lipgloss.Color("")` (no colour) per-theme instead, which leaves the
  #    other presets alone.
  #  - it was pointed at `onedark`, which is blue-leaning — the one thing this
  #    palette is explicitly trying not to be.
  #
  # Grounds are empty; raised surfaces (modal) and selections keep an opaque
  # fill on purpose, matching how the nvim glass snippet treats floats.
  #
  # Accents are the ghostty-glass ANSI palette, restated here because the
  # shared `themes/glass.nix` attrset only carries ground/text colours.
  glassTheme = t: ''
    # Glass — generated by modules/home/cli/superfile.nix. Do not edit here;
    # superfile only overwrites files that exist in its own embedded set, so
    # this one survives its theme extraction.

    code_syntax_highlight = "github-dark"

    # ========= Border =========
    file_panel_border = "${t.selection}"
    sidebar_border = "${t.selection}"
    footer_border = "${t.selection}"

    # ========= Border Active =========
    file_panel_border_active = "#9FB0C2"
    sidebar_border_active = "#B7A9C6"
    footer_border_active = "#8FCFB4"
    modal_border_active = "#9CBCC0"

    # ========= Background (bg) =========
    # Empty = no colour = the terminal's own translucent ground shows through.
    full_screen_bg = ""
    file_panel_bg = ""
    sidebar_bg = ""
    footer_bg = ""
    modal_bg = "${t.surface}"

    # ========= Foreground (fg) =========
    full_screen_fg = "${t.fishPrimary}"
    file_panel_fg = "${t.fishPrimary}"
    sidebar_fg = "${t.fishPrimary}"
    footer_fg = "${t.fishPrimary}"
    modal_fg = "${t.fg}"

    # ========= Special Color =========
    cursor = "${t.fg}"
    correct = "#8FCFB4"
    error = "#E8837A"
    hint = "#9CBCC0"
    cancel = "#D8BE96"
    gradient_color = ["#9FB0C2", "#B7A9C6"]

    # ========= File Panel Special Items =========
    file_panel_top_directory_icon = "#D8BE96"
    file_panel_top_path = "#B6C4D4"
    file_panel_item_selected_fg = "${t.fg}"
    file_panel_item_selected_bg = "${t.selection}"

    # ========= Sidebar Special Items =========
    sidebar_title = "#9FB0C2"
    sidebar_item_selected_fg = "${t.fg}"
    sidebar_item_selected_bg = "${t.selection}"
    sidebar_divider = "#3B3E44"

    # ========= Modal Special Items =========
    modal_cancel_fg = "${t.bg}"
    modal_cancel_bg = "#E8837A"

    modal_confirm_fg = "${t.bg}"
    modal_confirm_bg = "#8FCFB4"

    # ========= Help Menu =========
    help_menu_hotkey = "#9CBCC0"
    help_menu_title = "#B7A9C6"
  '';

  caseLines = lib.concatStringsSep "\n        " (lib.mapAttrsToList (n: spf:
    ''${n}) spf_theme="${spf}" ;;''
  ) superfileThemeMap);
in
{
  programs.superfile = {
    enable = true;
    settings = {
      editor = "nvim";
      dir_editor = "nvim";
      ignore_missing_fields = true;
      theme = "active";
    };
  };

  # superfile reads themes from ~/.config/superfile/theme, a directory it
  # populates itself on first launch. Writing into it is safe: its extraction
  # only creates files that exist in its embedded set, and `glass.toml` is not
  # one of them.
  xdg.configFile = lib.optionalAttrs (themes ? glass) {
    "superfile/theme/glass.toml".text = glassTheme themes.glass;
  };

  # Point ~/.config/superfile/theme/active.toml at the palette matching the
  # current theme. Superfile extracts its built-in themes to this dir on first
  # launch, so the symlink target may be created lazily — the activation
  # silently no-ops if the file isn't there yet.
  #
  # The name comes from ~/.local/state/quickshell/active-theme, which is what
  # theme-set writes and what the theme-driven CLI tools actually follow.
  # ~/.config/hypr/theme.conf is only a fallback for hosts that predate that
  # state file: presets which don't switch themes never update theme.conf, so
  # reading it first meant glass resolved as whatever hypr was last left on
  # (dark → onedark) and superfile never picked up its own palette.
  home.activation.syncSuperfileTheme = lib.hm.dag.entryAfter [ "writeBoundary" "initHyprTheme" ] ''
    STATE="$HOME/.local/state/quickshell/active-theme"
    HYPR_THEME="$HOME/.config/hypr/theme.conf"
    SPF_THEMES="$HOME/.config/superfile/theme"

    name=""
    if [ -r "$STATE" ]; then
      name=$(cat "$STATE")
    elif [ -L "$HYPR_THEME" ]; then
      name=$(basename "$(readlink "$HYPR_THEME")" .conf)
    fi

    if [ -n "$name" ] && [ -d "$SPF_THEMES" ]; then
      spf_theme="hacks"
      case "$name" in
        ${caseLines}
        *) ;;
      esac
      if [ -f "$SPF_THEMES/$spf_theme.toml" ]; then
        ln -sf "$SPF_THEMES/$spf_theme.toml" "$SPF_THEMES/active.toml"
      fi
    fi
  '';

  themeHooks.superfile = pkgs.writeShellScript "theme-hook-superfile" ''
    theme="$1"
    SPF_THEMES="$HOME/.config/superfile/theme"
    spf_theme="hacks"
    case "$theme" in
      ${caseLines}
      *) ;;
    esac
    if [ -f "$SPF_THEMES/$spf_theme.toml" ]; then
      ln -sf "$SPF_THEMES/$spf_theme.toml" "$SPF_THEMES/active.toml"
    fi
  '';
}
