# Disk layout for pod042-class machines.
# Consumed by `nixinstall pod042` at install time to partition and format.
# NOT imported by the running system — the live machine's filesystems are
# declared in hardware-configuration.nix (generated by nixos-generate-config
# at install time, with the actual disk's freshly-minted UUIDs).
{ disk ? "/dev/nvme0n1", ... }:

{
  disko.devices.disk.main = {
    type   = "disk";
    device = disk;
    content = {
      type = "gpt";
      partitions = {
        boot = {
          size = "1G";
          type = "EF00";
          content = {
            type         = "filesystem";
            format       = "vfat";
            mountpoint   = "/boot";
            mountOptions = [ "fmask=0077" "dmask=0077" ];
          };
        };
        swap = {
          size    = "17G";
          content = { type = "swap"; };
        };
        # Reserved space for a future Windows install (League / Valorant —
        # Vanguard rules out Wine/Proton). Disko creates the partition but
        # leaves it unformatted; the Windows installer can format/replace it.
        # Declared BEFORE root so root's `size = "100%"` consumes only the
        # remaining space, not the disk's tail.
        windows = {
          size = "200G";
          type = "0700"; # Microsoft basic data
        };
        root = {
          size    = "100%";
          content = { type = "filesystem"; format = "ext4"; mountpoint = "/"; };
        };
      };
    };
  };
}
